### ISSUE TITLE
Support image-based automation with PDFs (and others)

### ISSUE THREAD

**Issue by osrjv** [robocorp/rpaframework#103]
Currently, template matching and OCR are only supported in a desktop automation context, but a library (probably `RPA.Images`) should be made that supports the same functionality but with a user-given document instead.

**Comment by cmin764** [comment]
Closing this as won't fix since it was decided that for image-based PDFs (and other such documents), we should go through more accurate AI trained models using `RPA.DocumentAI`.

Let's sync with @tonnitommi first if we still think this effort should be supported by ourselves with local help from Tesseract and `rpaframework-recognition` as implied.
