### ISSUE TITLE
Excel.Files Create Worksheet with own name gives extra sheet with default name when working with xlsx 

### ISSUE THREAD

**Issue by Harm10** [robocorp/rpaframework#120]
If I do Create Workbook of type xlsx and after that Create Worksheet with my own sheet name I end up with a xlsx file that has sheets Sheet and my own chosen name.
If i do the same but with Create Workbook of type xls I only end up with a xls file with just 1 sheet named with my own chosen name.
Using
rpaframework                       7.0.5
rpaframework-core                  5.2.0

**Comment by osrjv** [comment]
I had a free minute to make a test case for this and it seems it doesn't replicate anymore. Possibly related to xlrd update a while back. Please re-open if you still have similar issues on the current rpaframework version.

**Comment by Harm10** [comment]
I reran my test and the problem is still there.
My version of xlrd 2.0.1 (and there is no update).
rpaframework is now on 9.3.4 and rpaframework-core 6.1.0
robotframework 4.0
python 3.7.9

Code I use:
`    RPA.Excel.Files.Create Workbook    path=D:\\RobotFramework\\Testfiles\\#Files\\newtest.xlsx    fmt=xlsx
    RPA.Excel.Files.Create Worksheet    harmtest
    RPA.Excel.Files.Save Workbook`

Could you please reopen this issue?

**Comment by osrjv** [comment]
Ah, it's now harmonized in the other direction, i.e. `Create workbook` always creates a default worksheet with name `Sheet` for both formats.

I'm not sure I want to _not_ have it, because:
- The openpyxl library we use for xlsx files seemed to fail in unexpected ways when there were no worksheets at all
- Lots of existing workflows depend on not having to call `Create worksheet` explicitly

Your use-case can be fixed by either not calling `Create worksheet` or by replacing it with:
```
Create workbook    path=${somepath}
Rename worksheet    Sheet    harmtest
Save workbook
```

**Comment by Harm10** [comment]
I understand the problem. Wouldn't it be wiser to make the sheet name mandatory on Create workbook?
