### ISSUE TITLE
Failed: ImportError: DLL load failed while importing win32ui

### ISSUE THREAD

**Issue by brje** [robocorp/rpaframework#132]
I'm new with RF and RPAframwork, the framework worked well until I updated Python 3.8 to 3.9.1. I had issues to get RF working until I uninstalled all parts of Python, RF, nodejs etc. and re-set environmental variables. Even how I have issue with rpaframework, always when I try to run robot including rpaframework libraries i got error: "Error in file ... on line 6: Importing test l
ibrary 'RPA.Desktop.Windows' failed: ImportError: DLL load failed while importing win32ui" Do you have any advice how could I solve the problem?

**Comment by osrjv** [comment]
Python 3.9 is not officially supported due to some upstream dependencies (https://github.com/robocorp/rpaframework/issues/69), but I haven't seen this problem before. I found a relevant issue though: https://github.com/mhammond/pywin32/issues/1593

Can you test if it starts working if you manually do `pip install pywin32==300`? I can bump that dependency for the next release if so.

**Comment by brje** [comment]
Thanks a lot upgrading to pywin32 300 worked. @osrjv

**Comment by osrjv** [comment]
I reopened, because I think it's still a valid issue.

**Comment by osrjv** [comment]
Fixed in release `7.4.0`
