### ISSUE TITLE
Dialogs File Input extended with option to get source directory?

### ISSUE THREAD

**Issue by Harm10** [robocorp/rpaframework#154]
This is an enhancement request for Dialogs Add File Input:
Can the Request Response be enhanced with the source directory used for uploading?

**Comment by Harm10** [comment]
Is this the right place to ask for enhancements?

**Comment by osrjv** [comment]
Yes, sorry, just been a busy week for everyone involved.

By source directory do you mean the default folder where the file browser opens? That's not possible to control with the current browser-based approach (it's a security feature of browsers). But it's a valid feature and it's very possible we'll change from browsers to native dialogs/windows at some point.

**Comment by Harm10** [comment]
No I mean the source directory the user picks the file from before it gets uploaded.

**Comment by osrjv** [comment]
That's what I was referring to as well.

**Comment by osrjv** [comment]
The whole dialogs library was re-written for release `10.0.0`, which also makes adding features easier. The relevant part for this issue is the argument `source` for the keyword `Add file input`.

**Comment by Harm10** [comment]
I cannot test as RPA.Dialogs is not loading in RIDE with error "FAILED RPA.Dialogs list index out of range".
Should I create a separate issue for this?

I am on RPA 10.0.1 and RPA Dialogs 0.2.2 on Python 3.7.9, robotframework 4.0 and RIDE 2.0b1

**Comment by Harm10** [comment]
This list index out of range needs the latest dev version of RIDE: 
`pip install -U https://github.com/robotframework/RIDE/archive/master.zip`

But..... did you do an overhaul of Dialogs? Create form is no longer there? Even so Request respons? Some attributes of Add file input are gone?
If so, shouldn't that give some conversion to people using those structures? Or at least a heads up?

Anyway the added source is very welcome but not exactly what I asked for. The source attribute sets a default directory. I want to receive the directory the user browsed to to pick the file(s). So that should end up in the result object somewhere.

**Comment by osrjv** [comment]
Yes, it is not keyword compatible. The backwards compatibility was going to break anyways due to functional changes, so the API was cleaned a bit in the same go. We follow semantic versioning, which means different major versions are not guaranteed to be backwards compatible.

Releases are announced in our developer Slack and listed at https://rpaframework.org/releasenotes.html. I documented changes also now in our forums: https://forum.robocorp.com/t/dialogs-library-changes-in-rpaframework-10-0-0/731 A big conversion table of added/removed/renamed keywords between versions would be nice, but I don't think anyone has had a chance to make something like that.

I misunderstood the issue a bit, but these changes also fix that use-case. If you don't give a target directory for file inputs, it will return a list of the original files instead. Then you can do what you want with the original paths.

**Comment by Harm10** [comment]
I will do a test to see whether I can use the output generated without a target directory specified.

My main development experience is in Mainframe land. If some software release there would be not downward compatible you could loose all your clients............. I understand now the GUI world is quite different :-)

**Comment by Harm10** [comment]
I can confirm that when you leave out target directory (hence parameter destination=) that it contains the selected files including their path.
