### ISSUE TITLE
PDF form field viewing is inconsistent on different viewers

### ISSUE THREAD

**Issue by mikahanninen** [robocorp/rpaframework#156]
Not sure if there is anything that can be done in `rpaframework` to fix this issue, but written down anyways as an known issue.

Related to saving form fields on `RPA.PDF` library and article https://robocorp.com/docs/development-guide/pdf/how-to-fill-pdf-forms.

Code below is in `rpaframework`  9.0.0 syntax
```robot
*** Settings ***
Library           RPA.PDF

*** Tasks ***
Fill a PDF containing a form and save a copy
    Open Pdf    RobotSpareBin_repair_form.pdf
    Set Field Value    Your name    John Doe
    Set Field Value    Warranty    Yes
    Set Field Value    Robot model name    Robositter
    Set Field Value    Describe the problem    The Robot does not want to start anymore!
    Save Field Values    output_path=Filled_In_PDF.pdf
```

[RobotSpareBin_repair_form.pdf](https://github.com/robocorp/rpaframework/files/6187779/RobotSpareBin_repair_form.pdf)
[Filled_In_PDF.pdf](https://github.com/robocorp/rpaframework/files/6187814/Filled_In_PDF.pdf)

Example code is setting checkbox field `Warranty`  as checked on the attached PDF document as checked and then saved.

The checkbox field on PDF Acroform fields is shown with some viewers and not with others.

On Windows

- [ ] Chrome
- [ ] Edge
- [x] Firefox

On MacOS

- [ ] Chrome
- [ ] Adobe Acrobat Reader DC
- [x] Safari
- [x] Preview

**Comment by cmin764** [comment]
I confirm the issue, but sometimes we also win with the other browsers on checkbox tick state display if we set the `use_appearances_writer=${True}` when calling [Save Field Values](https://robocorp.com/docs/libraries/rpa-framework/rpa-pdf/keywords#save-field-values).

Things may already changed in better given the latest `rpaframework-pdf` major release. (included in _main_ **20.x.x**)

**Comment by cmin764** [comment]
I tested this thoroughly and choosing the close it as **solved** since the ideal fix is to use `/Yes` as for the value of a checked checkbox instead of `Yes`.

- Robot [code](https://github.com/cmin764/robots/blob/main/pdf-parse/tasks.robot#L291-L301)
- [repair-form-filled.pdf](https://github.com/robocorp/rpaframework/files/10544094/repair-form-filled.pdf)


### `Yes`

Visible in VSCode only but not in rest of the apps:

<img width="944" alt="mac-vscode-yes-only" src="https://user-images.githubusercontent.com/709053/215700530-03430237-537d-48c0-b828-9b6c6b102864.png">

### `/Yes`

Not visible in VSCode as checked, but visible in most of the rest of the apps:

Windows Acrobat
<img width="904" alt="windows-acrobat" src="https://user-images.githubusercontent.com/709053/215700795-d52c204f-39b2-44cd-9053-ada0ea072d49.png">

Windows Edge
<img width="745" alt="windows-edge" src="https://user-images.githubusercontent.com/709053/215700767-6e3ee9e9-f5ad-45f1-b130-a9954750eac2.png">

Windows Firefox
<img width="1208" alt="windows-firefox" src="https://user-images.githubusercontent.com/709053/215700798-1bd8e04c-d57f-4694-8919-aca412bf78f5.png">

Mac Preview
<img width="1043" alt="mac-preview" src="https://user-images.githubusercontent.com/709053/215700782-42d71815-9c09-47b3-938d-08e61f139a08.png">

Mac Chrome
<img width="944" alt="mac-chrome" src="https://user-images.githubusercontent.com/709053/215700778-39546679-d19e-4b78-bd1e-95c57b2d26a9.png">

Mac Safari
<img width="1038" alt="mac-safari" src="https://user-images.githubusercontent.com/709053/215700791-32158306-a55d-4069-9365-deb59e2fa4fe.png">

----

When you manually click and tick the checkbox, you actually add a new object in the PDF structure which looks like this:
```
>> /T (Warranty) /AS /Yes /Ff 0 /V /Yes >>
```
instead of just changing the value inside the object. Sometimes you'll find the same checkbox object **twice**, where the first occurrence contains the `/Off` (not checked value) and the second one contains the newly added duplicate that this time contains a `/Yes` value. (and that renders the checkbox as displayed)
