### ISSUE TITLE
RPA.PDF.HTML To PDF keyword problem outputting table with multiple cells

### ISSUE THREAD

**Issue by mikahanninen** [robocorp/rpaframework#183]
Related to beginner's course. `Create File` step has been added for confirmation that HTML contains required data.

```robot
*** Keywords ***
Export The Table As A PDF
    Wait Until Element Is Visible    id:sales-results
    ${sales_results_html}=    Get Element Attribute    id:sales-results    outerHTML
    Create File    ${CURDIR}${/}output${/}sales_results.html    ${sales_results_html}    overwrite=True
    Html To Pdf    ${sales_results_html}    ${CURDIR}${/}output${/}sales_results.pdf

```
Last rpaframework release this has worked is 7.6.0.

**Comment by janipalsamaki** [comment]
Did some testing with this one. The issue seems to be the current `width` attribute in the HTML table columns. The value there used to work back in the day.

This means that the columns are super-wide now. Thus it seems only one column is included in the generated PDF (although all the columns are probably there, they just don't fit). Apparently, some PDF dependency has changed.

There's a PR going in soon that changes the HTML output of the table in question (https://github.com/robocorp/rsb-intranet/pull/20). After that is deployed, all the columns should fit again.

This means that we could ignore this issue here and close it. I can do the closing after the other PR is merged and we have verified that the change works in the prod site, too.

**Comment by janipalsamaki** [comment]
The above-mentioned update to the HTML table structure fixed the Beginners' course issue. Closing this issue.
