### ISSUE TITLE
RPA.Tables library keyword Get Table Column unexpected argument as_list

### ISSUE THREAD

**Issue by raivolink** [robocorp/rpaframework#186]
After upgrade to rpaframework 10.0.1 keyword results to error. 
_Keyword 'RPA.Tables.Get Table Column' expected 2 arguments, got 3._
Example: `${emails_as_list}    Get Table Column    ${expenses}    ${3}    as_list=True`
Python version 3.7.5
Win 10 version 20H2

**Comment by osrjv** [comment]
There were some fairly big changes for `RPA.Tables` in release `10.0.0`. Mainly the support for named rows was removed, since it was hard to understand and not that well documented. As a result certain arguments didn't make sense anymore, such as this one.

In its current state the keyword _always_ returns a list, so to fix this issue just use:
```
${emails_as_list}=     Get Table Column    ${expenses}    3
```

The release also added automatic type conversions wherever possible, so indexing columns should not require explicit integer variables anymore.
