### ISSUE TITLE
Environment variable from env.json is not found when using local (not generated) environment

### ISSUE THREAD

**Issue by adrian-evo** [robocorp/rpaframework#189]
Suppose I have devdata\env.json with the following content:

```
{
  "SERVER_URL": "https://robocorp.com/docs/development-howtos/variables-and-secrets/"
}

```

When using autogenerated environment, i.e. condaConfigFile: conda.yaml within robot.yaml, the following keyword is working:

`    New Page    %{SERVER_URL}
`

However, when not using conda.yaml but local Python installation with all needed stuff, the message is

`Environment variable '%{SERVER_URL}' not found.
`

Is this as expected?
When using hardcoded data instead of variable, the task is running, so there is no issue with local environment.

Second issue is that devdata\env.json is not read unless specified explicitly in command line, although I understood that this special file is always read if exists:

`rcc run -t Task -e devdata\env.json`

**Comment by osrjv** [comment]
Hi!

I think this isn't really the correct place for this, since this repository is only for the library project (RPA Framework). RCC has its own repository and issue tracker: https://github.com/robocorp/rcc, but this sort of touches Robocorp products as a whole so I recommend posting on the forums: https://forum.robocorp.com/

I can still try to answer to the best of my knowledge:

1. I'm not sure if that is expected as an end-user, but that's how it works currently. RCC manages the environment entirely and the environment variables are part of that operation. I think this is something that might change, but it may be worth it to document it on the RCC issue tracker separately.
2. The env.json file is a convention that is enforced within tools that use RCC internally, such as Robocorp Lab or the Robocorp VSCode extension. RCC itself is a lower-level building block and doesn't do that automatically.
