### ISSUE TITLE
Log level set to info after using 'Register Protected Keywords' keyword

### ISSUE THREAD

**Issue by BCE-Vincent** [robocorp/rpaframework#191]
I set the logging level to trace in the robot.yaml file. And in the setup suite i use the Register Protected Keywords keyword with one argument. The log level in log.html for the rest of the script is set to info. This Only occurs when the script is run from the cloud not localy in VSCode. The problem is solved by using the Set Log Level Keyword after the Register Protected Keywords.

**Comment by osrjv** [comment]
Hi, thanks for the report.

The keyword `Register protected keywords` should not change the log level immediately when run, so that might be a bit of a red herring. I however notice that there's a possibility of log levels not being restored correctly if there are nested keyword calls that change log levels.

**Comment by osrjv** [comment]
@BCE-Vincent, I released a new version of the `core` package. Can you try out adding `rpaframework-core==6.2.2` into your `conda.yaml` in addition to the existing RPA Framework, and then running the robot again? This should hopefully fix issues with wrong log levels.
