### ISSUE TITLE
Importing library 'RPA.Email.ImapSmtp' failed: ModuleNotFoundError: No module named 'RPA.Email' Error

### ISSUE THREAD

**Issue by sayom88** [robocorp/rpaframework#194]
Hello,
I have already setup robocop in my workspace from pip install rpaframework. 
Also installed 
pip install rpaframework-dialogs 
pip install rpaframework-google
pip install rpaframework-pdf
pip install rpaframework-recognition

Now when I am running my robot script, I am getting this below error:
 Importing library 'RPA.Email.ImapSmtp' failed: ModuleNotFoundError: No module named 'RPA.Email'

Attaching the robot script which I am using for this. Can you kindly help what needs to be done to fix this please?

[MailPoC.robot.txt](https://github.com/robocorp/rpaframework/files/6708474/MailPoC.robot.txt)

**Comment by osrjv** [comment]
Hi, thanks for the report.

Can you share these details:
- Current Python version: `python --version`
- Current pip version: `pip --version`
- Operating System name/version

Also, are you using an additional tool to manage environments, such as virtualenv or conda?
In general I would advise installing all packages in one `pip install` call, since that helps pip correctly resolve dependencies.

**Comment by sayom88** [comment]
Hello, here are the details :
   Current Python version: Python 3.9.1
    Current pip version: pip 21.0.1 from c:\users\sayomghosh\appdata\local\programs\python\python39\lib\site-packages\pip (python 3.9)
    Operating System name/version: Win10 64 bit

Also, are you using an additional tool to manage environments, such as virtualenv or conda? No

In general I would advise installing all packages in one pip install call, since that helps pip correctly resolve dependencies: Yes I have done that

**Comment by sayom88** [comment]
Hi @osrjv ,any updates on this?

**Comment by osrjv** [comment]
I managed to reproduce _a_ problem with a clean Windows 10 VM. It seems we have a relatively new dependency (pythonnet), which does not have prebuilt binaries for Python 3.9.

However it has a pretty prominent error when pip installing and that failure happens. Did you see any errors while installing? It shouldn't just cleanly finish but then fail on import...

Currently the fix is to either:
- Downgrade to a lower Python version (3.6 to 3.8)
- Install the visual studio build tools required to build the wheel, although I'm not exactly sure what the required toolchain is
- Wait for pythonnet to release a Python 3.9 compatible wheel

We have a job which checks python version compatibility, but apparently the runner manages to build the wheel just fine. I think we'll have to look at running it in a fresh VM as well.

**Comment by sayom88** [comment]
Hello @osrjv 

I have now downgraded to python 3.6 in my machine and ran the robot script. But still getting the same issue. Can you please help.
![image](https://user-images.githubusercontent.com/16284729/123949349-15587900-d9c0-11eb-89fa-b0aca62bd0d6.png)

**Comment by osrjv** [comment]
Alright, there seems to be something fundamentally broken here. Can you share what your log from `pip install` looks like when installing rpaframework? Is your pip using the same python binary that you're using for running?

I'd almost recommend posting to [our forums](https://forum.robocorp.com/) since there will be more people to help, and this doesn't seem to be exactly an issue with the libraries themselves.

**Comment by sayom88** [comment]
[pip command.txt](https://github.com/robocorp/rpaframework/files/6747962/pip.command.txt)

This is the log when i am installing pip install rpaframework

**Comment by osrjv** [comment]
After your downgrade you seem to be running pip 9.0.1 and like the error message says you should upgrade for cryptography to install.

So should hopefully work after: `python -m pip install --upgrade pip`

**Comment by sayom88** [comment]
I did that and now getting a different error. Fyi, i have already Microsoft Visual C++ 14.0 is my machine.
[pip command_1.txt](https://github.com/robocorp/rpaframework/files/6759772/pip.command_1.txt)

**Comment by DemBarros** [comment]
I have the same issue importing library 'RPA.Browser.Selenium'

on line 9: Importing library 'RPA.Browser.Selenium' failed: ModuleNotFoundError: No module named 'RPA.Browser'

Is this the same bug?

**Comment by Zaki-2** [comment]
i got also the same error too
![image](https://user-images.githubusercontent.com/11617832/144851350-44d02d87-b980-4368-922b-551551b6bba1.png)

**Comment by AlexisxCapto** [comment]
Hello,

I got the same error from those two packages:
from RPA.Excel.Files import Files
from RPA.Tables import Tables

ModuleNotFoundError: No module named 'RPA'

What is interesting is that I don't have this issue when I run the same query, same .py file on Robocorp Lab

**Comment by JWBWork** [comment]
Any progress on this?

Attempting `from RPA.Robocorp.Vault import Vault`
Results in `ModuleNotFoundError: No module named 'RPA'`

python and pip: 
python=3.8
pip=21.1

Pretty sure this is an issue with 3.8 so I'm downgrading to 3.7 for now, but I'd love to be able to keep using the f-string debugging with RPA

**Comment by mikahanninen** [comment]
@JWBWork I would recommend that you define also the minor version for Python in the conda.yaml.

Our official Robot template is setting Python version to 3.7.5 and it is already supporting f-strings and if I am not mistaken f-string support was already added to Python 3.6.

Minor version is important, because there have been at least 2 cases of Python versions which will cause issues with rpaframework .... the 3.7.6 and 3.8.1. 

Just tested with Python 3.8.5 and task run without issues.

```yaml
channels:
  - conda-forge
dependencies:
  - python=3.8.5
  - pip=20.1
  - pip:
    - rpaframework==12.8.2
```

**Comment by cmin764** [comment]
The templates just upgraded to the following _conda.yaml_ now, so please try using this and re-open the issue if you still experience importing issues:
```YAML
channels:
  # Define conda channels here.
  - conda-forge

dependencies:
  # Define conda packages here.
  # If available, always prefer the conda version of a package.
  # Installation will be faster and more efficient.
  # https://anaconda.org/search
  - python=3.9.13

  - pip=22.1.2
  - pip:
      # Define pip packages here.
      # https://pypi.org/
      - rpaframework==15.6.0 # https://rpaframework.org/releasenotes.html
```

**Comment by Surekha-tfs** [comment]
HI i am also facing the same issue"ModuleNotFoundError: No module named 'robocorp'"
 "from robocorp import windows"
python=3.12.2 
 pip=23.2.1

**Comment by Jayashree-Mohan** [comment]
Hi All,
Am also facing the same issue. IS it related to python version? does not support rpa framework?
It would be great if we get clear about the python, rpa framework version that is supported right now.
In my system i have dependencies as,
channels:
  - conda-forge

dependencies:
  - python=3.10.12                    # https://pyreadiness.org/3.10
  - pip=23.2.1                        # https://pip.pypa.io/en/stable/news
  - robocorp-truststore=0.8.0         # https://pypi.org/project/robocorp-truststore/
  - nodejs=18.19.0                    # https://github.com/nodejs/node/blob/main/CHANGELOG.md
  - pip:
    - robotframework-browser==17.5.2  # https://github.com/MarketSquare/robotframework-browser/releases
    - rpaframework==27.7.0            # https://rpaframework.org/releasenotes.html
    - oracledb==2.1.0
    - robotframework-databaselibrary==1.4.4
    - psycopg2-binary==2.9.9

rccPostInstall:  - rfbrowser init          
even i tried with 3.12 its the same issue. Previously it was working for the above versions, but now after reverting back it is also not working. (Note: previously it worked with above version)

**Comment by bryan6738** [comment]
I have same issue with RPA.Cloud.Google library. Who solved this issue?
