### ISSUE TITLE
Selenium Is detected by website and robocorp rpa automation fails..!!!

### ISSUE THREAD

**Issue by HarshilPatel007** [robocorp/rpaframework#201]
Robocorp uses the selenium for web automation. but, selenium is got detected now a days. example, https://www.aviationtrader.com.au/?gtmlt=1 and https://www.controller.com/ plus many more websites now has mechanism to detect selenium and our automation fails in that case.
Is there any solution to cope with this detection..????

**Comment by osrjv** [comment]
The way Selenium is detected on websites will differ based on the technology used. Some sites use simple user-agent detection, but others detect certain variables that webdriver sets in the browser window.

You can try changing the user-agent string, or using a different browser (e.g. firefox instead of chrome). Another option is to try to use https://github.com/MarketSquare/robotframework-browser instead of Selenium.

This isn't really a bug or something we can trivially fix on the library side, so I'm going to close this issue. However, I recommend posting on the Robocorp forums: https://forum.robocorp.com/
