### ISSUE TITLE
rpaframework is not fully compatible with Python 3.9 because of dependency pythonnet

### ISSUE THREAD

**Issue by far3ll** [robocorp/rpaframework#208]
rpaframework 11.0.0
Python 3.7.9, 3.8.10, 3.9.7
OS: Windows 10 with Visual Studio Build Tools 2019, "Desktop development with C++" installed

Documentation of rpaframework states compatibility of Python >= 3.6 (so including Python 3.9), but dependency "pythonnet" version 2.5.2 only supports up to Python 3.8.
During installation via pip, following errors occur:

```
  Build FAILED.

  "C:\Users\u20e00\AppData\Local\Temp\pip-install-mfmzwq4y\pythonnet_bbe73cc22323470e94f3b54a1212b5fc\pythonnet.sln" (Build target) (1) ->
  "C:\Users\u20e00\AppData\Local\Temp\pip-install-mfmzwq4y\pythonnet_bbe73cc22323470e94f3b54a1212b5fc\src\runtime\Python.Runtime.csproj" (default target) (2) ->
  (CoreCompile target) ->
    CSC : error CS1617: Invalid option '7.3' for /langversion; must be ISO-1, ISO-2, 3, 4, 5 or Default [C:\Users\u20e00\AppData\Local\Temp\pip-install-mfmzwq4y\pythonnet_bbe73cc22323470e94f3b54a1212b5fc\src\runtime\Python.Runtime.csproj]


  "C:\Users\u20e00\AppData\Local\Temp\pip-install-mfmzwq4y\pythonnet_bbe73cc22323470e94f3b54a1212b5fc\pythonnet.sln" (Build target) (1) ->
  "C:\Users\u20e00\AppData\Local\Temp\pip-install-mfmzwq4y\pythonnet_bbe73cc22323470e94f3b54a1212b5fc\src\clrmodule\clrmodule.csproj" (default target) (6) ->
    CSC : error CS1617: Invalid option '6' for /langversion; must be ISO-1, ISO-2, 3, 4, 5 or Default [C:\Users\u20e00\AppData\Local\Temp\pip-install-mfmzwq4y\pythonnet_bbe73cc22323470e94f3b54a1212b5fc\src\clrmodule\clrmodule.csproj]

      0 Warning(s)
      2 Error(s)
```
On Python 3.7 and 3.8, everything works as expected.

Also see https://github.com/pythonnet/pythonnet/issues/1262 for this.

Any method to circumvent this issue (beside downgrading to Python 3.8)?

**Comment by osrjv** [comment]
I know it's a matter of semantics, but rpaframework itself is compatible with Python 3.9, and we run our tests in CI with it. The GitHub runners just happen to have the correct toolchain for building the missing wheels. I can't really help with the build errors from pythonnet, but it looks like you don't have new enough compilers.

On our end I can think of three things we can do:
1. Wait for pythonnet to publish pre-built wheels
2. Start using conda as the main distribution method instead of pip
3. Not include rpaframework-dialogs in the main package, as that seems to be the dependant

Possibly all three.

**Comment by osrjv** [comment]
I changed how parts of the packaging work and as a result pythonnet should not be a dependency on Windows anymore. Our CI still doesn't replicate the original issue, but feel free to reopen if you keep having issues.
