### ISSUE TITLE
Tables does not support ${my_table}[10][A] -style column indexing

### ISSUE THREAD

**Issue by orlof** [robocorp/rpaframework#210]
Tables does not support ${my_table}[10][A] -style column indexing

**Comment by osrjv** [comment]
Easily fixable by changing the table getter to return dicts instead of lists, but it's not backwards compatible. Can do the change and wait for the next major release.

In python you can say `table[10, "A"]`, but that of course doesn't work with RF's special bracket syntax. Currently in RF you need to use `Get table cell`.

**Comment by osrjv** [comment]
Implemented (and fixed unittests) in 9e18d30d7b856981935c850bf8590504c2999c0b

Will be merged when we next break backwards compat.
