### ISSUE TITLE
RPA.JSON: Convert Dictionary to JSON?

### ISSUE THREAD

**Issue by Harm10** [robocorp/rpaframework#213]
I am trying to create JSON to send to another platform. For this I have created a dictionary. As such a dictionary holds the keys and values within single quotes I get an error when trying to convert it to JSON using Convert string to JSON: JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)

Would it be possible to update RPA.JSON in some way so this conversion can normally be done?

**Comment by osrjv** [comment]
The naming might not be the best, but...

The keyword `Convert string to JSON` takes a string and parses it as if it were JSON into a Python object.
It should work if you give the dictionary to `Convert JSON to string`, which creates a JSON string from the given object (assuming the contents can be represented as JSON).

What's happening in your case is that Robot Framework is calling `str()` on your dictionary, because the argument requires a string. That means it's a Python literal with single quotes, which it then tries to parse as (invalid) JSON.

**Comment by Harm10** [comment]
I understand your explanation. But it is a bit weird that you need to code JSON to string to end up with a json string to deliver to the request that needs it?

As a temporary workaround I can now use json.dumps(${dictionary}) to get a double quoted string. Warning! If you use json.dumps("""${dictionary}""") you end up with a string that has single quotes!

**Comment by osrjv** [comment]
I think you misunderstood a bit. With `Convert string to JSON` the library loads JSON strings into a a Python object that it also happens to call JSON. With those objects you can use the other keywords like `Get values from JSON`.

The keyword `Convert JSON to string` takes that _Python object_ and converts it into a JSON string, that you can send somewhere else. It is effectively nothing else but a wrapper to `json.dumps`.

`json.dumps("""${dictionary}""")` will fail for the same reason I mentioned, because RF will replace that variable value with it's `str()` representation (that has single quotes).

**Comment by osrjv** [comment]
With that library keyword naming convention in mind, this should work just fine:
```
${json_object}=      Create dictionary    key=value
${json_string}=      Convert JSON to string    ${json_object}
```

Also `json.dumps("""${dictionary}""")` is doing something you might not expect. First RF replaces the variable with the string representation of your dict (e.g. `json.dumps("""{'key': 'value'}"""`) and then evaluates it through Python. It creates a valid JSON string, but it's one where the root object is a string and not a map (`"{'key': 'value'}"`). A JSON can have any scalar as a root (boolean, int, string), not just list or map.

Newlines etc. in a JSON string should be fine. If you have an example of the code and a traceback, make a separate issue.
