### ISSUE TITLE
RPA.Excel.Files handling of errors?

### ISSUE THREAD

**Issue by Harm10** [robocorp/rpaframework#223]
I am using RPA.Excel.Files (RPA 10.9.1).
How is an user supposed to handle errors? For example Open Workbook does not seem to return if an Excel is already opened by another process (I get a general error with a somewhat weird error text). Should we use general keywords of Robotframework to catch errors? Or is there some other way?

Also the available commands seem to change in the different versions? And the documentation also seems to be not up-to-date? For example read [https://rpaframework.org/libraries/excel_files/python.html](url)

**Comment by Harm10** [comment]
When can I expect a reply?

**Comment by osrjv** [comment]
Sorry, yes, this issue tracker is mostly used for bugs and tracking development tasks, and I personally have been working on other projects. In general questions and developer support is handled either in our [forums](https://forum.robocorp.com/) or [public slack](https://robocorp-developers.slack.com/).

As for some quick answers to your questions:
1. Error handling will have to happen by the user somehow. There are multiple things that can fail (like the other process thing you have, permissions, network errors, malformed files, etc.), and many of them are not fixable on the library level. Currently you will have to use the general RF keywords for catching errors, if it's something you want to catch. Sometimes the only option is to just fail and fix something manually. We are also pushing for better try/catch support into RF itself, and that should be released with 5.0.
2. New keywords are added with new versions, yes, and sometimes changed/removed between major versions. However, I don't think any backwards non-compatible changes have been made in the Excel.Files library (at least for a long time). rpaframework.org _should_ have versioned documentation, but other issues have been more urgent. The linked documentation seems to be correct for the _Python_ API though. If you want the latest RF documentation, it's here: https://rpaframework.org/libraries/excel_files/index.html

**Comment by Harm10** [comment]
Thanks for your response. Your public slack is not entirely public as you can only register with specific mail address domains?

I understand that you cannot cope with each imaginable error situation but some basic catches would greatly enhance the framework in my view.

I am not sure whether the Excel.files was the one with some downward incompatibility but I am certain one of the RPA framework did. Doing so often could lead to users leaving this package if they use it in a production like environment.

And although I understand creating and updating documentation is much work I still think such updates should be categorized as Urgent too. The documentation you are linking to also misses out on several things.........
Perhaps you should let users do updates to the documentation too? As soon as they encounter important errors they can suggest an update?

**Comment by osrjv** [comment]
I don't think our Slack should have any requirements on mail address domains, unless there are some global limitations on Slack's end. It should only require a valid Slack account. Is there some specific error?

Managing between changes that are not backwards compatible and moving forwards is a bit of a balancing act. Especially since RPAFW has a lot of API surface, and any change in the ~800 keywords can make the whole library "backwards incompatible" to a degree. We follow semantic versioning for that reason, i.e. major versions need care to upgrade, but any minor/patch version should be safe.

For a production environment it's a **must** to lock down to specific versions of any libraries, not just this one. The overall Python community is just very bad at this, because historically the tooling for managing dependencies has been abysmal.

Agree on the importance of documentation, but even urgent issues have an order. They are coming up in the roadmap though. And this project is on GitHub for a reason and we will gladly take in PRs of library or documentation changes.
