### ISSUE TITLE
RPA.Excel Files openpyxl warning not supported extension

### ISSUE THREAD

**Issue by Harm10** [robocorp/rpaframework#262]
When I read a worksheet I get this warning:
c:\python3\lib\site-packages\openpyxl\worksheet\_reader.py:312: UserWarning: Conditional Formatting extension is not supported and will be removed

When investigating on the net I see that several extensions can give this warning. I also see that openpyxl offers an option to only read the data from the worksheet. RPA.Excel Files does not have such an option.

So I have 2 questions:
1. What will happen if openpyxl drops the support entirely? Will read worksheet fail?
2. Can a parameter be added to read worksheet (and perhaps other commands as well) to only read data?

I am on rpaframework 10.9.3 and openpyxl 3.0.7

**Comment by osrjv** [comment]
As for question #1, as I understood it it's referring to custom workbook extensions that can be embedded into the Excel XML file. It looks like openpyxl is a bit misleading with its error since it doesn't support them at all, and `will be removed` doesn't refer to some future library version but what's happening when it reads the file.

**Comment by tonnitommi** [comment]
If latest versions still have the issue, please reopen this.
