### ISSUE TITLE
Windows library keyword `Get Window Elements` fails when using `elements_to_json=True`

### ISSUE THREAD

**Issue by mikahanninen** [robocorp/rpaframework#267]
```
*** Settings ***
Library           RPA.Desktop.Windows

*** Tasks ***
Minimal task
    Open Dialog    windowtitle=Processed    wildcard=True
    ${elements}=    Get Window Elements    element_json=True
    FOR    ${elem}    IN    @{elements}
        Log To Console    ${elem}
    END
    Log    Done.
```

Error message
`TypeError: Object of type WindowSpecification is not JSON serializable`

**Comment by developer-iname** [comment]
Any update to this bug, what priority level does it have, is it worth adding a conditional skip for WindowSpecification in the "write_element_info_as_json()"? 
I'm not too familiar with pywinauto. Is there a reason why WindowSpecification is needed, is it required to be parsed in order to manipulate the attributes of the window.

**Comment by cmin764** [comment]
Since `RPA.Desktop.Windows` got deprecated in favor to `RPA.Windows`, I guess that the new [library](https://robocorp.com/docs/libraries/rpa-framework/rpa-windows) can be used instead and this Issue discarded.
