### ISSUE TITLE
RPA.Tasks applied to subtasks of a keyword

### ISSUE THREAD

**Issue by sahokas** [robocorp/rpaframework#27]
Improvement idea from support channel:

1. For one side DataDriver applies a Keyword (called the "Test Template") to a collection of data, all running a test independently of each other.  So if one fails, the rest are allowed to run and resolve on their own terms regardless.

2. On the other hand, you have RPA.Tasks, that allows to define an execution flow via a JSON file, referred to as the "schema".

They're both are incompatible to each other, given that both take ownership of the flow of tasks... and here's the suggestion:

Wouldn't it be nice to have something like RPA.Tasks that instead of applying to the Tasks section it applied to the subtasks of a keyword?  Like the Template Keyword used by DataDriver... this way you could have tests running independently of each other and at the same time, define the execution flow via a schema.

**Comment by osrjv** [comment]
I think this would be interesting to have. Especially since there's no way to run the same suite multiple times inside one execution. As it stands, the only way to achieve this is to do the looping outside of Robot Framework and then use rebot to combine logs.

Unfortunately with the current listener API it is not possible to modify the execution model for individual keywords. I'll however keep this issue open so that we can take a look when support for it is added.

**Comment by mikahanninen** [comment]
Do you @osrjv and @sahokas that this issue is still valid? If not I will close the issue.

**Comment by osrjv** [comment]
I don't think it's really relevant with our current plans. We should focus on work items and process level flows.
