### ISSUE TITLE
Code smell in Database library

### ISSUE THREAD

**Issue by orlof** [robocorp/rpaframework#282]
This if -structure is suspiciuous: https://github.com/robocorp/rpaframework/blob/5ca25d88793c042748091a677cc73a956da31be2/packages/main/src/RPA/Database.py#L520

It's basically:
```
IF SOMETHING1 AND SOMETHING2
  DO_IT
IF SOMETHING2
  DO_IT
```

**Comment by cmin764** [comment]
Indeed, very [fishy](https://github.com/robocorp/rpaframework/blob/5ca25d88793c042748091a677cc73a956da31be2/packages/main/src/RPA/Database.py#L520-L524), wondering what was the original intention as it's clearly a logical bug there since the block suggests a different intention compared to actual behaviour.

**Comment by cmin764** [comment]
Tackling this at the same time with the other related one: https://github.com/robocorp/rpaframework/issues/286
