### ISSUE TITLE
Add support for managing already open applications

### ISSUE THREAD

**Issue by mikahanninen** [robocorp/rpaframework#361]
### Related scenario.

In a Robot `RPA.Desktop.Open Application` is used to open application if it is not open. The `Open Application` returns application instance with `_proc `property which instance of `subprocess.Popen`.

There is no supported way at the moment (in the RPA.Desktop library) to Close Application which is already open, because keyword requires application instance returned by the Open Application.

### Workaround to close application

```python
    FOR    ${w}    IN    @{window_list}
        IF    "${w}[title]" == "APPLICATION TITLE"
            ${command}=    Set Variable    os.kill($w["pid"], signal.SIGTERM)
            Evaluate    ${command}    signal
        END
    END
```

- [x] introduce easy application management pattern for rpaframework which would work between libraries
- [x] if above task is not easily achievable then introduce a simpler way to close already application

**Comment by cmin764** [comment]
The problem with the above workaround is if you mix it with `RPA.Windows` controlling keywords, you'll end up in a state which produces **COMError** next time you control some other window due to context not being cleaned-up, like `Close Current Window` is doing already.

So I feel this one translates best into these two separate issues:
1. https://github.com/robocorp/rpaframework/issues/368
2. https://github.com/robocorp/rpaframework/issues/369

Opinions?
