### ISSUE TITLE
`Set Download Directory` Keyword doesn't change download directory

### ISSUE THREAD

**Issue by vincentmathis** [robocorp/rpaframework#412]
I tried setting the default download directory, `${DOWNLOAD_DIR}` contains the current working directory. The browser downloads the file without problem but it's always in `C:\Users\xxxx\Downloads`

I followed this example https://robocorp.com/docs/development-guide/browser/how-to-change-browser-download-directory

```ROBOT
*** Variables ***
${FILENAME}      filename.pdf
${DOWNLOAD_DIR}    ${CURDIR}

*** Tasks ***
Download CSV Reports from Kibana
    Open Download Website
    Download File From Website
    Log    Done.

*** Keywords ***
Open Download Website
    Set Download Directory    ${DOWNLOAD_DIR}
    Open Browser    https://xxxxx    chrome    options=add_argument("--ignore-certificate-errors")

Download File From Website
    Click Link    xyz/filename.pdf
    Wait for Download To Complete

Wait For Download To Complete
    Wait Until Keyword Succeeds
    ...    2 min
    ...    5 sec
    ...    File Should Exist
    ...    ${FILENAME}
```

**Comment by mikahanninen** [comment]
@vincentmathis Hi. It is **not** good practise to name user keyword with the same name as library keyword (**Open Browser**). I guess in this case the keyword `Open Browser` you have defined in the `*** Keywords ***` is not called at all. Instead `RPA.Browser.Selenium.Open browser` is called and `Set Download Directory` is never called.

**Comment by vincentmathis** [comment]
Oh this was just a mistake because I didn't want to post sensitive information. I didn't actually name the user keyword "Open Browser", sorry about the confusion.

**Comment by mikahanninen** [comment]
Ok ;) Well this worked for me..

```robotframework
*** Settings ***
Library           RPA.Browser.Selenium
Library           OperatingSystem

*** Variables ***
${FILENAME}       generated.pdf
${DOWNLOAD_DIR}    ${CURDIR}

*** Tasks ***
Download CSV Reports from Kibana
    Open Download Website
    Download File From Website
    Log    Done.

*** Keywords ***
Open Download Website
    Set Download Directory    ${DOWNLOAD_DIR}
    Open Available Browser    https://github.com/robocorp/rpaframework/blob/master/packages/main/tests/resources/generated.pdf

Download File From Website
    Click Element    //a[@id="raw-url"]
    Wait for Download To Complete

Wait For Download To Complete
    Wait Until Keyword Succeeds
    ...    2 min
    ...    5 sec
    ...    File Should Exist
    ...    ${FILENAME}

```

**Comment by vincentmathis** [comment]
I can confirm that your robot works as expected. The only difference I could find is that you are using `Open Available Browser` instead of `Open Browser`.

The problem is that I explicitly chose `Open Browser` chrome so I can pass `--ignore-certificate-errors` as launch argument, otherwise I can't access my target website.

**Comment by mikahanninen** [comment]
@vincentmathis the `Set Download Directory` works with` Open Available Browser`. To make this work with `Open Browser` keyword, you need to set following Chrome preferences:

```python
"download.default_directory": "ABSOLUTE_PATH_TO_DIR",
"plugins.always_open_pdf_externally": True/False,
"download.directory_upgrade": True,
"download.prompt_for_download": False,
```

**Comment by vincentmathis** [comment]
I found a way to pass these preferences and can confirm that this works. Thank you for the help.

It would be helpful to note that `Set Download Directory` only works with `Open Available Browser` on this page: https://robocorp.com/docs/development-guide/browser/how-to-change-browser-download-directory

**Comment by HaritYadav** [comment]
@vincentmathis Can you share an example of how you made this work? I have to use ‘Open Browser’ as I need to specify the executable path too.

**Comment by simonpfrank** [comment]
In case it helps (and this answer is not for Robot Framework.  I had problems with this in python and rpaframework. I remember from doing some raw Selenium that if you set the download directory after having opened the browser it doesn't take. So in rpframework browser.set_download_directory(path) needs to be before open_available_browser() or open_browser(). This is why although the preference seems to be set Selenium ignores it.

**Comment by cmin764** [comment]
A few notes based on the feedback provided above:

1. Yes, the setting of the download folder should happen before opening the browser, because the opening itself instructs where to download and how to behave with such explicit configuration. (and it can't listen for it during the run itself, has to be started instructed like so)
2. Such custom configuration can be passed with the `Open Available Browser` keyword as well through the `options` param exactly as you do with `Open Browser`, so we recommend using our **OAB** helper keyword as much as you can since it is taking care of lots of things for you, including the automating web-driver download.
3. If you're relying on `executable_path` to pass a custom web-driver binary to run the browser with (thus being forced to use `Open Browser`), remember that you can put the `chromedriver` in PATH in the robot structure and that one would be used prior the downloaded/cached one ensured by the **OAB** keyword. Ensure you set `download=${False}` just to be sure this doesn't get accidentally downloaded, please check these recent docs: [Open Available Browser](https://robocorp.com/docs/libraries/rpa-framework/rpa-browser/keywords#open-available-browser). (and check our Portal [example](https://robocorp.com/portal/robot/robocorp/example-ie-mode-edge) as well on how we deal with various settings like options, custom browser binary and executable path)
4. We recently [released](https://robocorp-developers.slack.com/archives/CH1GSKER0/p1678688929428409) a new version improving the behavior with the latest `rpaframework==22.2.2`, so please update to that first.

If you encounter any other issues, please open a thread on our [Forum](https://forum.robocorp.com/c/troubleshooting/15). Happy automation!
