### ISSUE TITLE
`RPA.Robocorp.WorkItems` control structures inside `For Each Input Work Item` loop

### ISSUE THREAD

**Issue by blakewaud** [robocorp/rpaframework#535]
Currently, robot developers must manually handle controlling program flow when something causes the robot to need to stop processing a work item during a loop of `For Each Input Work Item`. Usually this is because the work item has failed somehow, so a dev would need to release that work item and then reset the environment for the next work item and then stop the loop.

This can be tricky if the execution is in a deeply nested keyword as the dev would need to consider this logic in every preceding keyword so the control propagates up to the task level.

We need to be able to essentially use `CONTINUE` or something like it so that the control can return to the `For Each Input Work Item` wrapper and restart processing. It would be best if intervening teardowns all ran as well to ensure the environment is ready for the next work item.

**Comment by cmin764** [comment]
Since we want to be able to _break_/_continue_ the loop from any point in the code, I feel the simplest & safest option is to craft two keywords like:
- `Break Work Items Loop`
- `Continue Work Items Loop`

Where both of them raise an exception handled by the `For Each Input Work Item` helper internally, then this decide if it continues with the next item or just stops the execution. No matter if all the items in the queue are consumed/skipped OR if the loop is stopped, rest of the code continues to execute unaffected by the loop's flow trajectory.

**Comment by blakewaud** [comment]
Would the `For Each Input Work Item` helper be able to run the keyword teardowns? I suppose it's not a huge loss if they can't be ran, but I imagine that if a dev can configure the teardown to always do the work of returning the system to a "ready" state for the next work item, that would be the easiest and most like other patterns in Robot Framework.

**Comment by cmin764** [comment]
Closing this as `won't fix` since the better pattern for solving this is the TRY-EXCEPT as showcased in this [PR](https://github.com/robocorp/template-producer-consumer/pull/2).
