### ISSUE TITLE
RPA.PDF KW Convert

### ISSUE THREAD

**Issue by extmme** [robocorp/rpaframework#540]
Hi there,

I am not sure what KW Convert (RPA.PDF) should do... 
Should it return a converted PDF?
How should I work with this KW in the next steps???

Thank you

**Comment by cmin764** [comment]
Hi, you don't usually need to call this keyword [Convert](https://robocorp.com/docs/libraries/rpa-framework/rpa-pdf/keywords#convert) yourself as other dependent keywords will call it for you, like:
- [Find Text](https://robocorp.com/docs/libraries/rpa-framework/rpa-pdf/keywords#find-text)
- [Get Text From Pdf](https://robocorp.com/docs/libraries/rpa-framework/rpa-pdf/keywords#get-text-from-pdf)
- [Dump Pdf As Xml](https://robocorp.com/docs/libraries/rpa-framework/rpa-pdf/keywords#dump-pdf-as-xml)

And because the conversion takes a while, you might control when you want to do it (before calling the dependent keywords), gladly this happens only once.
