### ISSUE TITLE
`RPA.JSON` RecursionError: maximum recursion depth exceeded

### ISSUE THREAD

**Issue by mikahanninen** [robocorp/rpaframework#548]
This error is at the moment breaking our [Certificate level 3](https://robocorp.com/docs/courses/work-data-management/validate-business-data) course with `rpaframework==15.0.0`.

Works correctly with `rpaframework==14.0.0`

```
*** Keywords ***
Validate traffic data
    [Arguments]    ${traffic_data}
    ${country}=    Get Value From Json    ${traffic_data}    $.country
    ${valid}=    Evaluate    len("${country}") == 3
    RETURN    ${valid}
```

example content of `${traffic_data}`
```
  {
      "country": "ISR",
      "year": 2019,
      "rate": 3.90874
  }
```

**Comment by mikahanninen** [comment]
Duplicate of #537

**Comment by cmin764** [comment]
The regression was introduced with `rpaframework==14.2.0` given this [line](https://github.com/robocorp/rpaframework/pull/509/files#diff-759fffbba9b8e0532ccd65c2fc0a4a53c585e556177877d5b11af50d9edee7dfR13) since it produces the infinite recursion straight from _libspec_, as can be seen with both rcc and VSCode:
<img width="644" alt="Screenshot 2022-06-17 at 10 46 47" src="https://user-images.githubusercontent.com/709053/174254623-d008a2d1-0258-482d-98e3-3c35b2ac8fa7.png">

Wasn't caught through unit/robot tests since this doesn't replicate in CI/locally:
```bash
python -m robot -L TRACE --outputdir output --logtitle "Task log" --task "Validate traffic data" tasks.robot
```
just works given this [task](https://github.com/cmin764/robots/blob/main/json-path/tasks.robot#L25-L29). (since it doesn't invoke any _libspec_ parsing I believe)
