### ISSUE TITLE
`RPA.Email.Exchange` code example(s) & docstrings should use OAuth2

### ISSUE THREAD

**Issue by tonnitommi** [robocorp/rpaframework#604]
https://github.com/robocorp/rpaframework/blob/02f90774c15d9b2f9e7d90f74ab30d9f47d63d3b/packages/main/src/RPA/Email/Exchange.py#L91

Exchange basic authentication flow will be [deprecated](https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/deprecation-of-basic-authentication-exchange-online) from October 1st, 2022. The examples should be updated to use Oauth2 Auth Code flow.

Example here: https://robocorp.com/portal/robot/robocorp/example-oauth-email

**Comment by cmin764** [comment]
Since the flow isn't trivial, we can reference the OAuth2 type of [authorization](https://github.com/robocorp/example-oauth-email/blob/master/tasks.robot#L73-L80) and we link the Portal example for rest of the code.

We might be lucky enough to be able to still use Exchange with [App Passwords](https://support.microsoft.com/en-gb/account-billing/manage-app-passwords-for-two-step-verification-d6dc8c6d-4bf7-4851-ad95-6d07799387e9) even after that date. (and as @sahokas suggested in a demo, we should take this security compromise instead of generating confusion and support tickets)

**Comment by cmin764** [comment]
Since App Passwords can't be used anymore with `Exchange`, it really makes sense to adapt the entire docstirng and examples to the OAuth2 flow.
