### ISSUE TITLE
On the last leg of a project and am struggling to finish this one

### ISSUE THREAD

**Issue by petahmars** [robocorp/rpaframework#614]
I'm new to robocorp and using it on VS Code.  I need to upload the most recent file from my download folder on my local drive or on my chrome browser.  Here are a couple pictures showing where I'm at.  I'm not sure if "Choose File" is the correct step on robocorp.  Specifically I am stuck on what I put for locator.  Thanks for any help.

<img width="1440" alt="Screen Shot 2022-08-30 at 10 23 19 PM" src="https://user-images.githubusercontent.com/96781727/187599559-28a1df53-a826-4796-8b86-0da9d297755a.png">

<img width="690" alt="Screen Shot 2022-08-30 at 10 23 39 PM" src="https://user-images.githubusercontent.com/96781727/187599598-d70e022f-d1dc-40da-8d38-1fb9c10a66b6.png">

**Comment by cmin764** [comment]
Hi @petahmars 

Is advised to use our [forum](https://forum.robocorp.com/) for such questions if you don't have any issue (like a bug or error) to post related to the library usage. If you're not sure, ask there first and then we'll see if there's a problem with the library code or just a support case.

----

From what I see, [Select From List By Label](https://robocorp.com/docs/libraries/rpa-framework/rpa-browser-selenium/keywords#select-from-list-by-label) is just ticking on items in a list.

In order to upload a file, I believe [Choose File](https://robocorp.com/docs/libraries/rpa-framework/rpa-browser-selenium/keywords#choose-file) is what you're looking for. As for the locator, can you provide to us the HTML partial content (or the website link if is public) which contains that field so we can help with the craft of it? (otherwise use our Robocorp extension tool in VSCode called "Web Locators" to pick and even store them conveniently)
