### ISSUE TITLE
`RPA.Windows` keyword `Windows Search` is too quick

### ISSUE THREAD

**Issue by blakewaud** [robocorp/rpaframework#654]
When using the `Windows search` keyword, depending on system performance and the status of the search index, Windows may take some time to find the object being searched for, but the sleep is after clicking `{enter}`. I believe that may be a bug, but in any case, we need to be able to set a sleep between entering the search term and clicking enter.

**Comment by cmin764** [comment]
Additionally, while at this, the `RPA.Windows.keywords.action` module should suffer the following refactor:
```python
wait_time or self.ctx.wait_time  # bugged when `wait_time` is 0 (aka no wait at all)
```
to
```python
wait_time if wait_time is not None else self.ctx.wait_time
```
so I'm going to add back the **bug** label because of this.

**Comment by cmin764** [comment]
@blakewaud Go ahead and create a PR if you have some extra time since it sounds like an easy fix. Afterwards you can test it on a Windows machine with a command like `inv code.test-robot -r windows -t "Play Task Calculator"`.

**Comment by blakewaud** [comment]
Do we really need a wait after clicking enter? The library has built in timeouts for finding elements, so theoretically, if you called `Control window` after `Windows search`, it should have the current global timeout to wait for the app to open... and you could set that before opening the app if you know the app is slow. Otherwise I agree and can look at this next after MSGraph.

**Comment by cmin764** [comment]
You have a point here and technically this is desirable, but by design our `wait_time` philosophy here is the amount of seconds to sleep after a command completely finishes and that's totally up to the user if he/she wants to override the default. Also there's no guarantee that somebody will call `Control Window` (or anything related relying on timeouts) after such `Windows Search` execution, so maybe somebody just wants to open an app and at the same time set a sleep time long enough for the effect to be observed, place where sleeping at the end of the command execution makes sense.

Anyway, how would you improve this patch suggestion to make it even more versatile?
```python
        self.ctx.send_keys(keys=search_cmd)
        self.ctx.send_keys(keys=text, interval=0.1, wait_time=wait_time)  # this is what solves the issue
        self.ctx.send_keys(keys="{Enter}")
        time.sleep(wait_time if wait_time is not None else self.ctx.wait_time)  # since we will allow default context time waits here as well (more flexibility)
```

Of course, the downside is that there are two identical sleeps now: one between finishing typing & pressing Enter and another at the end of the command chain.
