### ISSUE TITLE
RPA.Notifier Notify Telegram returning True when failing to send message

### ISSUE THREAD

**Issue by celsocontim** [robocorp/rpaframework#969]
When the telegram notification is blocked due to network restrictions, it throws the error:
 
Notify errors: ["HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6089576190:AAFwnNJuOE7gTFnnHOy06ZXiXMovDrnHByU/sendMessage (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:997)')))"]

However, the return value of the keyword is still True, as can be seen in the screenshot attached.

RPAFramework 23.1.0
Python 3.10.7
OS Windows 10 Pro

![error_telegram](https://github.com/robocorp/rpaframework/assets/55033856/9136ea2f-2519-4074-965e-ef9ba95a7fb2)

**Comment by cmin764** [comment]
Well, this works exactly as expected, as you don't call `Notify Telegram` directly, you wrap it instead with the `Run Keyword And Return Status` which will never fail (thus status is always `True`), because `Notify Telegram` doesn't raise in this case and returns a status instead, according to the response handler logic:
```python
    def _handle_response(self, response) -> bool:
        if response.status == "Success":
            self.logger.info("Notify %s resulted in Success", response.provider)
            return True
        else:
            self.logger.error("Notify errors: %s", response.errors)
            return False
```

To fix it, you have two options:
- A. Remove `Run Keyword And Return Status` wrapper and use the status received when calling directly the keyword.
- B. Replace your wrapper with [`Run Keyword And Ignore Error`](https://robocorp.com/docs/libraries/built-in/builtin/keywords#run-keyword-and-ignore-error) and pay attention to the second return value:
<img width="772" alt="Screenshot 2023-05-24 at 10 34 27" src="https://github.com/robocorp/rpaframework/assets/709053/4ffca804-61ed-4c74-ac59-47b4e87fd487">


I'll be closing this now as it doesn't look like an issue/bug with our library.
