### ISSUE TITLE
Cryptography dependency causes SNYK alert - upgrade to newer version

### ISSUE THREAD

**Issue by tonnitommi** [robocorp/rpaframework#979]
User got a SNYK alert about dependency vulnerability. The issue is with `cryptography` package. The recommended action is to update this package to version `>=41.0.0`. The latest `rpaframework` version have dependency limit for `cryptography<41.0.0` and `>=40.0.2`.

https://security.snyk.io/vuln/SNYK-PYTHON-CRYPTOGRAPHY-5663682

**Comment by cmin764** [comment]
Are we sure we want to have a floating **major** version? As letting that upgrade automatically freely might introduce breaking changes (semver). Anyway, this "limitation" has to be reflected in `rpaframework-pdf` _poetry.lock_ as well, otherwise, you'd still have the restriction in place at Poetry level at least. (during development)

Here's a [bump](https://github.com/robocorp/rpaframework/pull/936/files) from the past from **39** -> **40** for reference.
